config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "pages#index"

  devise_for :users, path: "", controllers: { omniauth_callbacks: 'auth/omniauth_callbacks' }

  get 'login_as', to: 'debug#login_as' if ENV["DEBUG_LOGIN_INTO_ACCOUNT"]

  namespace :student, module: "students" do
    root to: "root#show"
    get "(/*any)" => "root#show"
  end

  namespace :teacher, module: "teachers" do
    root to: "students#index"

    resources :students, only: %i[index]
    resources :surveys
  end

  resources :polls, only: [:show]

  resources :stages do
    get :statistics, on: :member
  end

  resources :surveys do
    get :results, on: :member
    get :respondents, on: :member
  end

  # Admin
  namespace :admin do
    root to: "base#index"

    namespace :support do
      resource :merge_faculties, only: [:show] do
        post :execute
      end
    end

    resources :polls do
      resources :poll_options, module: :polls
      put :archive, on: :member
    end

    resources :stages
    resources :students do
      resources :raw_teachers, only: [:index], module: :students
    end
    resources :teachers
    resources :questions
    resources :faculties
    resources :users do
      get "admins", action: :index, on: :collection
      get ":kind", action: :index, on: :collection
    end

    namespace :reports do
      resources :teachers, only: [:index] do
        get :lack_of_participations, on: :collection
        get :lack_of_students, on: :collection
      end
      resources :faculties, only: [:index]
    end
  end

  # API
  namespace :api, defaults: {format: :json} do
    namespace :students_api do
      resources :polls, only: [:index, :show] do
        resource :vote, only: [:create], module: 'polls'
      end

      resources :stages do
        resources :teachers, module: 'stages', only: [:index, :show] do
          resource :feedback, module: 'teachers', only: [:show, :create]
          resource :relation, module: 'teachers', only: [:create, :destroy]

          post :refresh, on: :collection
        end

        resource :roster, module: 'stages/teachers', only: [:show]
      end
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :faculty_participants, class_name: 'Poll::FacultyParticipant', dependent: :destroy
  has_many :options, class_name: 'Poll::Option', dependent: :destroy
  has_many :faculties, through: :faculty_participants
  has_many :answers, class_name: 'Poll::Answer', dependent: :destroy
  has_many :participations, class_name: 'Poll::Participation', dependent: :destroy

  scope :active, -> { where('starts_at < ?', Time.current).where('ends_at > ?', Time.current) }
  scope :not_archived, -> { where(archived_at: nil) }

  def self.for_student(student)
    most_recent_faculty = GradeBook.most_recent_for(student: student)&.faculty_id
    not_archived.joins(:faculties).where(faculties: { id: most_recent_faculty }).distinct
  end

  def student_participated_in_poll?(student)
    Poll::Participation.find_by(student: student, poll: self).present?
  end

  def current?
    current_time = Time.current
    starts_at <= current_time && current_time <= ends_at
  end

  def archived?
    archived_at.present?
  end

  def upcoming?
    Time.current < starts_at
  end

  def started?
    starts_at < Time.current
  end

  def finished?
    ends_at < Time.current
  end

  alias_method :past?, :finished?
end

app/models/poll/answer.rb
class Poll
  class Answer < ApplicationRecord
    self.table_name = "poll_answers"

    belongs_to :poll
    belongs_to :poll_option, class_name: "Poll::Option"
  end
end

app/models/poll/faculty_participant.rb
class Poll
  class FacultyParticipant < ApplicationRecord
    self.table_name = "poll_faculty_participants"

    belongs_to :poll
    belongs_to :faculty
  end
end

app/models/poll/option.rb
class Poll
  class Option < ApplicationRecord
    self.table_name = "poll_options"
    include ::ImageUploader::Attachment(:image)

    belongs_to :poll
    has_many :answers, class_name: 'Poll::Answer', foreign_key: 'poll_option_id'

    def proportion
      answers_by_poll = poll.answers.count.to_f

      return 0 if answers_by_poll == 0

      (answers.count.to_f / answers_by_poll) * 100
    end
  end
end

app/models/poll/participation.rb
class Poll
  class Participation < ApplicationRecord
    self.table_name = "poll_participations"

    belongs_to :poll
    belongs_to :student
  end
end

app/controllers/admin/polls/poll_options_controller.rb
module Admin
  module Polls
    class PollOptionsController < Admin::BaseController
      authorize_resource class: 'Poll::Option'

      def new
        @poll = Poll.find(params[:poll_id])
        @poll_option = Poll::Option.new
      end

      def create
        @poll = Poll.find(params[:poll_id])
        ::Polls::AsAdmin::AddOptionToPoll.new.call(create_params.to_h) do |monad|
          monad.success do
            respond_with(:success, 'Вариант ответа успешно добавлен к голосованию')
          end
          monad.failure(:poll_not_started) do
            respond_with(:error, 'Нельзя добавлять варианты к существующему голосованию')
          end
          monad.failure do
            respond_with(:error, 'Во время сохранения варианта ответа возникли ошибки')
          end
        end
      end

      def destroy
        @poll = Poll.find(params[:poll_id])

        @poll_option = Poll::Option.find(params[:id])
        @poll_option.destroy

        respond_with(:success, 'Вариант ответа успешно удален из голосования')
      end

      private

      def respond_with(kind, msg)
        flash[kind] = msg
        redirect_to admin_poll_path(@poll)
      end

      def create_params
        params.require(:poll_option).permit!.merge(poll: @poll)
      end
    end
  end
end

app/controllers/admin/polls_controller.rb
module Admin
  class PollsController < Admin::BaseController
    load_and_authorize_resource

    def new
      @poll = Poll.new
      @faculties = Faculty.all.order(name: :asc)
    end

    def create
      ::Polls::AsAdmin::CreatePoll.new.call(create_params.to_h) do |monad|
        monad.success do |result|
          respond_with(:success, 'Голосование успешно создано')
          redirect_to admin_poll_path(result[:poll])
        end
        monad.failure(:starts_in_future) do
          respond_with(:error, 'Пожалуйста, укажите дату не раньше завтрашней')
        end
        monad.failure(:dates_are_valid) do
          respond_with(:error, 'Пожалуйста, убедитесь, что дата начала предшествует дате завершения')
        end
        monad.failure(:all_faculties_are_present) do
          respond_with(:error, 'Пожалуйста, убедитесь, что вы выбрали факультеты, которые могут участвовать в голосовании')
        end
        monad.failure do
          respond_with(:error, 'Во время сохранения опроса возникли ошибки')
          redirect_to new_admin_poll_path
        end
      end
    end

    def index
      @polls = @polls.order(starts_at: :desc)
    end

    def show
      @options = @poll.options
    end

    def archive
      @poll.update(archived_at: Time.current)

      redirect_to admin_polls_path
    end

    def destroy
      ::Polls::AsAdmin::RemovePoll.new.call(poll: @poll) do |monad|
        monad.success do |result|
          respond_with(:success, 'Опрос успешно удален')
          redirect_to admin_polls_path
        end

        monad.failure do
          respond_with(:error, 'К сожалению, уже невозможно удалить этот опрос')
          redirect_to admin_poll_path(@poll)
        end
      end
    end

    private

    def respond_with(kind, msg)
      flash[kind] = msg
    end

    def create_params
      parameters = params.require(:poll).permit!

      parameters[:faculty_ids] = parameters[:faculty_ids].map(&:presence).compact.map(&:to_i)

      parameters
    end
  end
end

app/controllers/api/students_api/polls/votes_controller.rb
module Api
  module StudentsApi
    module Polls
      class VotesController < BaseController
        def new
          @poll_options = poll.options
        end

        def create
          ::Polls::AsStudent::LeaveVoice.new.call(create_params) do |monad|
            monad.success { head :created }
            monad.failure(:poll_not_closed_yet) { respond_with_errors(['К сожалению, данное голосование больше не принимает голоса']) }
            monad.failure(:student_not_participated_before) { respond_with_errors(['Кажется, что Вы уже приняли участие в этом опросе'])  }
            monad.failure(:student_allowed_to_leave_voice) { respond_with_errors(['К сожалению, Вы не можете принимать участие в этом опросе']) }
            monad.failure { respond_with_errors(['Мы не смогли принять Ваш голос :( Пожалуйста, обратитесь в техническую поддержку.']) }
          end
        end

        private

        def poll
          @poll ||= Poll.find(params[:poll_id])
        end

        def create_params
          {
            student: current_kind,
            poll: poll,
            poll_option: poll.options.find(params[:poll_option_id])
          }
        end
      end
    end
  end
end

app/controllers/api/students_api/polls_controller.rb
module Api
  module StudentsApi
    class PollsController < BaseController
      def index
        @polls = Poll.for_student(current_kind).active
      end

      def show
        @poll = Poll.find(params[:id])
      end
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def show
    @poll = Poll.find_by(id: params[:id])
  end
end

app/views/admin/polls/index.html.slim
.page-header
  h1.page-header-title Голосования
  .page-header-lead
    p Здесь можно управлять голосованиями, проводимыми на структурных поразделениях.
  ul.nav.nav-pills.page-header-actions.d-flex.justify-content-end
    li.nav-item
      = active_link_to 'Новое голосование', new_admin_poll_path, class: 'nav-link', role: 'button'

.list-group
  - @polls.each do |poll|
    = link_to admin_poll_path(poll), class: 'list-group-item list-group-item-action flex-column align-items-start' do
      h5.mb-2
        | #{poll.name} #{"[Архив]" if poll.archived?}
      p.mb-0.text-muted Голосование с #{l(poll.starts_at, format: :only_date)} по #{l(poll.ends_at, format: :only_date)}

app/views/admin/polls/new.html.slim
.page-header
  h1.page-header-title Новое голосование

= form_for(@poll, url: admin_polls_path) do |f|
  .form-group
    div.mb-1 Укажите название для голосования
    = f.text_field :name, class: 'form-control'

  .form-row.mb-3
    .col
      div.mb-1 Дата начала
      = f.text_field :starts_at, class: 'form-control', type: "date", min: (Time.current + 1.day).strftime("%Y-%m-%d")
    .col
      div.mb-1 Дата завершения
      = f.text_field :ends_at, class: 'form-control', type: "date", min: (Time.current + 2.days).strftime("%Y-%m-%d")

  .form-group
    div.mb-1 Выберите, на каких факультетах проводится голосование
    = f.collection_select :faculty_ids, @faculties, :id, :name, {}, class: 'form-control', multiple: true, style: "height: 400px;"
    .text-muted.mt-1
      small С помощью <code>Ctrl+Левая кнопка мыши</code>/<code>Cmd+Левая кнопка мыши</code> можно выбрать
                    несколько вариантов, а с помощью <code>Ctrl+A</code>/<code>Cmd+A</code> – все варианты из списка

  .form-grop
    = f.submit 'Создать голосование', class: 'btn btn-primary'

app/views/admin/polls/show.html.slim
.page-header
  h1.page-header-title Голосование
  .page-header-lead
    p
      | #{@poll.name} #{"[Архив]" if @poll.archived?}
  ul.nav.nav-pills.page-header-actions.d-flex.justify-content-end
    - unless @poll.archived?
      li.nav-item
        = form_for @poll, url: archive_admin_poll_path(@poll), method: :put do |f|
          = f.submit 'Архивировать', class: 'nav-link btn', data: { confirm: 'Вы уверены?' }
    li.nav-item
      = form_for @poll, url: admin_poll_path(@poll), method: :delete do |f|
        = f.submit 'Удалить', class: 'nav-link btn btn-danger', data: { confirm: 'Вы уверены?' }

.mb-3
  h4.mb-1 Варианты ответа / кандидаты
  - unless @poll.started?
    = active_link_to 'Добавить вариант ответа', new_admin_poll_poll_option_path(@poll), class: 'btn btn-primary', role: 'button'
.list-group.mb-3
  - @options.each do |option|
    div class='list-group-item list-group-item-action'
      .d-flex.flex-row.align-items-center
        div.mr-3 style="width: 100px; height: 100px; background-image: url('#{option.image_url}'); background-color: #eee; background-size: cover; background-repeat: no-repeat;"
        div style='flex: 1;'
          h5.mb-2 = option.title
          p.mb-0 = option.description
        div
          p.mb-0.text-muted #{number_to_percentage(option.proportion)} (#{option.answers.count})
          - unless @poll.started?
            = form_for @poll, url: admin_poll_poll_option_path(@poll, option), method: :delete, html: { class: 'mt-2' } do |f|
              = f.submit 'Удалить', class: 'btn btn-sm btn-danger'

.mb-3
  h4.mb-1 Подразделения-участники
ul
  - @poll.faculties.each do |faculty|
    li = faculty.name