config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "pages#index"

  devise_for :users, path: "", controllers: { omniauth_callbacks: 'auth/omniauth_callbacks' }

  get 'login_as', to: 'debug#login_as' if ENV["DEBUG_LOGIN_INTO_ACCOUNT"]

  namespace :student, module: "students" do
    root to: "root#show"
    get "(/*any)" => "root#show"
  end

  namespace :teacher, module: "teachers" do
    root to: "students#index"

    resources :students, only: %i[index]
    resources :surveys
  end

  resources :polls, only: [:show]

  resources :stages do
    get :statistics, on: :member
  end

  resources :surveys do
    get :results, on: :member
    get :respondents, on: :member
  end

  # Admin
  namespace :admin do
    root to: "base#index"

    namespace :support do
      resource :merge_faculties, only: [:show] do
        post :execute
      end
    end

    resources :polls do
      resources :poll_options, module: :polls
      put :archive, on: :member
    end

    resources :stages
    resources :students do
      resources :raw_teachers, only: [:index], module: :students
    end
    resources :teachers
    resources :questions
    resources :faculties
    resources :users do
      get "admins", action: :index, on: :collection
      get ":kind", action: :index, on: :collection
    end

    namespace :reports do
      resources :teachers, only: [:index] do
        get :lack_of_participations, on: :collection
        get :lack_of_students, on: :collection
      end
      resources :faculties, only: [:index]
    end
  end

  # API
  namespace :api, defaults: {format: :json} do
    namespace :students_api do
      resources :polls, only: [:index, :show] do
        resource :vote, only: [:create], module: 'polls'
      end

      resources :stages do
        resources :teachers, module: 'stages', only: [:index, :show] do
          resource :feedback, module: 'teachers', only: [:show, :create]
          resource :relation, module: 'teachers', only: [:create, :destroy]

          post :refresh, on: :collection
        end

        resource :roster, module: 'stages/teachers', only: [:show]
      end
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/controllers/admin/support/merge_faculties_controller.rb
module Admin
  module Support
    class MergeFacultiesController < Admin::BaseController
      def show
        @faculties = Faculty.all.order(name: :asc)
      end

      def execute
        raise CanCan::AccessDenied unless can?(:merge_faculties, current_user)

        ::Faculties::AsAdmin::MergeDuplicatedFacultyToAnotherFaculty.new.call(call_params) do |monad|
          monad.success do
            flash[:success] = 'Структурные подразделения успешно объединены'
            redirect_to admin_support_merge_faculties_path
          end
          monad.failure do
            flash[:error] = 'Не удалось объединить выбранные факультеты'
            redirect_to admin_support_merge_faculties_path
          end
        end
      end

      private

      def call_params
        {
          faculty: Faculty.find_by_id(execute_params[:faculty_id]),
          duplicated_faculty: Faculty.find_by_id(execute_params[:duplicated_faculty_id])
        }
      end

      def execute_params
        params.require(:tool).permit!
      end
    end
  end
end

app/views/admin/support/merge_faculties/show.html.slim
.page-header
  h1.page-header-title Объединение структурных подразделений
  .page-header-lead
    p Если из чьей-то зачетки в 1С:Университет поступили устаревшие данные о названии факультета, то этот инструмент
      помогает решить эту проблему.

.alert.alert-warning role='alert'
  | Внимание! Изменения, которые вносятся этим инструментом, необратимы. Выбирайте мудро.

= form_tag execute_admin_support_merge_faculties_path, method: :post do |f|
  .form-group
    div Выберите актуальное название факультета
    = collection_select :tool, :faculty_id, @faculties, :id, :name, {prompt: 'Выберите факультет, в который нужно влить данные'}, class: 'form-control'

  .form-group
    div Выберите старое название факультета
    = collection_select :tool, :duplicated_faculty_id, @faculties, :id, :name, {prompt: 'Выберите факультет, который будет влит в выбранный выше'}, class: 'form-control'
  = submit_tag 'Объединить факультеты', class: 'btn btn-primary'